FROM ghcr.io/openhands/agent-server:1.10.0-python

USER root

RUN mv /usr/local/bin/openhands-agent-server /usr/local/bin/openhands-agent-server-orig

COPY containers/app/agent-server-pp-wrapper.sh /usr/local/bin/openhands-agent-server
RUN chmod +x /usr/local/bin/openhands-agent-server

USER openhands
